language: go

dist: trusty

go:
- "1.9"
- "1.10"
- "1.11"
- "tip"

env:
  - GIMME_OS=linux GIMME_ARCH=amd64

cache: apt

before_install:
  - go get -u github.com/golang/dep/cmd/dep

install:
  - dep ensure

script:
  - make
  - go test -race -coverprofile=coverage.out -covermode=atomic .
