language: go

dist: trusty

go:
- 1.8
- 1.9
- tip

env:
  - GIMME_OS=linux GIMME_ARCH=amd64

cache: apt

before_install:
  - go get -u github.com/golang/dep/cmd/dep

install:
  - dep ensure

script:
  - make
  - go test -race -coverprofile=coverage.out -covermode=atomic .
